apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-management
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: studentdb
  MYSQL_USER: student
  MYSQL_PASSWORD: student123