# spring.application.name=student-management

# server.port=8082


# spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
# spring.datasource.username=${DB_USERNAME:student}
# spring.datasource.password=${DB_PASSWORD:student123}

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=student-management

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

